### ISSUE TITLE
Use node IDs when processing node lists

### ISSUE THREAD

**Issue by gfanti** [gfanti/bitcoin#5]
Elsewhere when we need to do processing outside use the node ids, e.g. when you collect the candidate nodes, collect their ids. Then pick an id. and when you loop over the nodes for the send, use the id. cfields may have better advice since the recent changes to the peer handling API are his.

(thanks gmaxwell for this suggestion)

**Comment by amiller** [comment]
Also from Greg's message.... this is still relevant:
`The candidates set really should exclude the peer the transaction was just received from. It should probably also consider the peer's fee-filter-- no reason to send a transaction that will just be rejected.`

**Comment by amiller** [comment]
This is now addressed in, which reworks the mechanism for randomly choosing stem nodes. Now the stem nodes are chosen from a set of two dedicated "stem nodes", which are re-randomized every few minutes (every 10 minutes on a timer). The processing of choosing stem nodes avoids relying on any `CNode` pointers used outside a lock   https://github.com/gfanti/bitcoin/commit/b785c3fedccf5b1977020a670d2209d3a0623312#diff-eff7adeaec73a769788bb78858815c91R3209
